micronaut:
  application:
    name: petClinicReviews
  server:
    port: 8083
kafka:
  bootstrap:
    servers: localhost:9094
#mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
mongodb:
#  uri: mongodb://username:password@localhost:27017/pet-clinic-reviews
  uri: mongodb+srv://priestalesso:auditek1@alessocluster.qorik.mongodb.net/pet-clinic-reviews?retryWrites=true&w=majority
  databaseName: pet-clinic-reviews
  collectionName: vet-reviews
