micronaut:
  application:
    name: petClinicReviews
  server:
    port: 8083
kafka:
  bootstrap:
    servers: localhost:9094
#mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
mongodb:
  #username and password is the one granted in the securty option
  uri: mongodb+srv://alesso:auditek1@alessocluster.g1xq4.mongodb.net/?retryWrites=true&w=majority
  databaseName: pet-clinic-reviews
  collectionName: vet-reviews
