micronaut:
  application:
    name: petClinic
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/petclinic
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

kafka:
  bootstrap:
    servers: localhost:9094