package com.bonobo.micronaut.util;

import com.bonobo.micronaut.web.rest.errors.BadRequestException;

public class ResourceUtil {
    private ResourceUtil() {
    }

    public static void checkNoId(Long id, String entityName) {
        if (id != null) {
            throw new BadRequestException("New " + entityName + " cannot have an id. The ID is generated by DB engine.", entityName, "id_exists");
        }
    }

    public static void checkId(Long id, String entityName){
        if (id == null) {
            throw new BadRequestException("Invalid id", entityName, "id_null");
        }
    }

}
