micronaut:
  application:
    name: petOwner
  security:
    enabled: true
    authentication: session
    session:
      enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true

identity-store:
  users:
    alice: alice@1
    bob: bob@2
    charlie: charlie@3
  roles:
    alice: ADMIN
    bob: VIEW
    charlie: VIEW

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/petclinic
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    schema: petowner

jpa:
  default:
    entity-scan:
      packages:
        - com.bonobo.micronaut.domain
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
        show_sql: true
        default-schema: petowner