micronaut:
  application:
    name: petOwner
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/petclinic
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    schema: petowner

jpa:
  default:
    entity-scan:
      packages:
        - com.bonobo.micronaut.domain
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
        show_sql: true
        default-schema: petowner