POST http://{{host}}/api/owners
Content-Type: application/json

{
  "firstName": "Cristi",
  "lastName": "Arde",
  "address": "My Address",
  "city": "My City",
  "telephone": "31453546757"
}

> {%
 client.test("ID not found", function (){
    client.assert(response.status === 201, "Owner created")
    client.assert(response.headers.valueOf("X-petOwner-params") != null, "New ID was created")
    client.assert(response.headers.valueOf("X-petOwner-alert") === "petOwner.Owner.created", "HttpResponse.created")
});

 %}

###
GET http://{{host}}/api/owners/9999999
Accept: application/json

> {%
 client.test("ID not found", function (){
    client.assert(response.status === 404, "Page not found")
    client.assert(response.body["id"] == null, "ID does not exits")
});

 %}

###
GET http://{{host}}/api/owners/1
Accept: application/json

> {%
client.test("Fetch owner id 1", function (){
    client.assert(response.status === 200, "Result is ok")
    client.assert(response.body["id"] === 1, "Owner id = 1")
});
 %}

###
GET http://{{host}}/api/owners
Accept: application/json

> {%
client.test("Owners is not empty", function (){
    client.assert(response.status === 200, "Result is ok")
    client.assert(response.headers.valueOf("PAGE_COUNT") > 0, "Result is not empty")
});
 %}




